# zmodload zsh/zprof

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="honukai"

plugins=(git zsh-syntax-highlighting zsh-autosuggestions)

# export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=2,bg=cyan,bold,underline"

source $ZSH/oh-my-zsh.sh

source $HOME/dotfiles/zsh/env.zsh
source $HOME/dotfiles/zsh/options.zsh
source $HOME/dotfiles/zsh/alias.zsh
source $HOME/dotfiles/zsh/bindings.zsh
source $HOME/dotfiles/zsh/functions.zsh

# zprof
