# zmodload zsh/zprof
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="honukai"

plugins=(git zsh-syntax-highlighting zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

source $HOME/dotfiles/zsh/env.zsh
source $HOME/dotfiles/zsh/options.zsh
source $HOME/dotfiles/zsh/alias.zsh
source $HOME/dotfiles/zsh/bindings.zsh
source $HOME/dotfiles/zsh/functions.zsh

[ -s "$HOME/.scm_breeze/scm_breeze.sh" ] && source "$HOME/.scm_breeze/scm_breeze.sh"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh" || true

# zprof
